steps:
- name: gcr.io/cloud-builders/docker
  id: docker-build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA', '-f', 'Dockerfile', '.']
  env: ['PROJECT_ROOT=github.com/teltech/slack-break-bot']

- name: gcr.io/cloud-builders/docker
  id: docker-push
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  id: deploy
  args: ['set', 'image', 'deployment/${_DEPLOYMENT_NAME}', 'github-teltech-slack-break-bot-master=gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=common'

- name: 'gcr.io/cloud-builders/kubectl'
  id: check-rollout
  args: ['rollout', 'status', 'deployment/${_DEPLOYMENT_NAME}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=common'

#Pushing to Container Registry
images: ['gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA']
